name: fmea-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - sqlalchemy=2.0.22
  - psycopg2=2.9.9
  - python-dotenv=1.0.0
  - alembic=1.12.0
  - pytest=7.4.3
  - pip:
    # API dependencies
    - fastapi==0.104.1
    - uvicorn==0.23.2
    - pydantic==2.4.2
    - httpx==0.25.0
