name: fmea-tracker
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.13
  - sqlalchemy>=2.0
  - psycopg>=3.1
  - python-dotenv>=1.0
  - pytest>=8.0
  - alembic>=1.13
  - fastapi>=0.104.0
  - uvicorn>=0.24.0
  - pydantic>=2.5.0
  - httpx>=0.25.0
