version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: fmea_tracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-fmea_tracker}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-fmea_tracker}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
